[build-system]
requires = ["scikit-build-core>=0.8", "pybind11>=2.11"]
build-backend = "scikit_build_core.build"

[project]
name = "xrobotoolkit_sdk"
version = "1.0.2"
requires-python = ">=3.10"

[tool.scikit-build]
wheel.install-dir = "."
